name: Trigger auto deployment for kebs2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Dockerfile/**'
    - '.github/workflows/kebs2-AutoDeployTrigger-a2e48375-b242-4cdf-8225-d9828ee929cd.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: testkebs.azurecr.io
          username: ${{ secrets.KEBS2_REGISTRY_USERNAME }}
          password: ${{ secrets.KEBS2_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: testkebs.azurecr.io/kebs2:${{ github.sha }}
          file: Dockerfile/Dockerfile
          context: Dockerfile/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KEBS2_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n kebs2 -g testRG --server testkebs.azurecr.io --username  ${{ secrets.KEBS2_REGISTRY_USERNAME }} --password ${{ secrets.KEBS2_REGISTRY_PASSWORD }}
            az containerapp update -n kebs2 -g testRG --image testkebs.azurecr.io/kebs2:${{ github.sha }}
